name: test

on:
  # Trigger workflow on pull requests to the main branch
  pull_request:
    branches:
      - main
  # Trigger workflow on push to the main branch
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8.18"  # Use your project’s Python version

    # Step 3: Install Poetry
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.8.4 python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    # Step 4: Install dependencies
    - name: Install dependencies
      run: |
        poetry install --with dev

    # Step 5: Run Tests
    - name: Run tests
      run: |
        poetry run pytest -s --cov=biasanalyzer --cov-config=.coveragerc
